### ISSUE TITLE
Model trained on FlyingChairs

### ISSUE THREAD

**Issue by Choneke** [daigo0927/PWC-Net_tf#6]
Is there anyone who can share the model trained on FlyingChairs dataset?

Also with the model_3000epoch trained on SintelDataset, what is the last value of loss and epe you obtained?

**Comment by daigo0927** [comment]
I believe that the [original implementation of NVlabs](https://github.com/NVlabs/PWC-Net) contains the trained model (parameters) on FlyingChairs dataset.

and I'm sorry, I forget the exact value of loss and epe, but I'm guessing that they were a little worse than those stated in the original paper, (maybe because of dense connection of the network which is not implemented in mine).

**Comment by Choneke** [comment]
Oh, thank you very much.
